name: CD - Projeto Chat (Docker)

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name:  Mostrar versão do Docker
        run: docker --version

      - name: Checkout do código
        uses: actions/checkout@v4

      - name:  Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Build da imagem Docker
        run: docker build -t jefferson1707/projeto_chat:latest .

      - name:  Push da imagem para o Docker Hub
        run: docker push jefferson1707/projeto_chat:latest
