name: CI - Projeto Chat

# ğŸ”¹ Quando o pipeline deve rodar:
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸ Faz checkout do cÃ³digo
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      # 2ï¸ Configura o Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3ï¸Instala dependÃªncias
      - name: Instalar dependÃªncias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4ï¸ Executa os testes
      - name: Rodar testes automÃ¡ticos
        run: |
          pytest -v || echo " Nenhum teste encontrado ou erro em testes"
